Remove on cleanup too
CFC-Servers/cfc_map_scripts pull request #7
Opened 2024-10-13 21:00 UTC by StrawWagen

2024-10-13 21:01 UTC, brandonsturgeon requested changes

2024-10-13 21:01 UTC, brandonsturgeon commented on lua/map_scripts/utils.lua
> +end )
Put in init file instead please 👍

2024-10-13 21:02 UTC, StrawWagen commented on lua/map_scripts/utils.lua
> +end )
👍

2024-10-16 04:20 UTC, brandonsturgeon approved these changes
We might see some errors when a map cleanup happens - we'll handle them when they come up 👍

2024-10-16 04:20 UTC, merged